version: "3"

services:

  web:
    container_name: web
    image: web:test    
    build:
      context: ./web/
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:buster

  nginx:
    container_name: nginx
    image: nginx:test
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - web
    links:
      - web
